In [1]:
#11.Index-wise multiplication:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

index_wise_multiplication = A * B
print("Index-wise Multiplication:\n", index_wise_multiplication)


Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [2]:
#2.Matrix multiplication:
matrix_multiplication = np.dot(A, B.T)  # B.T is the transpose of B
print("Matrix Multiplication:\n", matrix_multiplication)


Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [3]:
#3.Add both matrices:
matrix_addition = A + B
print("Matrix Addition:\n", matrix_addition)


Matrix Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [4]:
#4.Subtract matrix B from A:
matrix_subtraction = A - B
print("Matrix Subtraction:\n", matrix_subtraction)


Matrix Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
#5.Divide Matrix B by A:
matrix_division = B / A
print("Matrix Division:\n", matrix_division)


Matrix Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
